FROM docker:dind

RUN apk update && apk upgrade

RUN apk --no-cache add nodejs npm python3 py3-pip gcc musl-dev python3-dev

RUN pip install aws-sam-cli awscli

RUN npm install -g cdk

WORKDIR /usr/src/app

COPY ./ /usr/src/app/
