name: Deploy to AWS

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
            docker ps
